import { Inter} from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/Theme-provider";
import Header from "@/components/Header";
import { ClerkProvider } from "@clerk/nextjs";
import page from "./page";
const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   <ClerkProvider>
    <html lang="en"suppressHydrationWarning>
      <body
        className={`${inter.className}`}
      >
         <ThemeProvider attribute = "class"
         defaultTheme = "dark">
          <Header />
          <main className="min-h-screen bg-zinc-50 dark:bg-black">
            
        {children}
        </main>
        <footer className="bg-muted/50 py-12 ">
         <div className="container mx-auto px-4 text-center text-gray-200">
          <p>For any Information reach out to github.com/devansh-7-gte</p>
         </div> 
        </footer>
        </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
